version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - blog-network

  blog-backend:
    image: canhnd15/blog-backend:1.0.2
    container_name: blog-backend
    ports:
      - "8090:8090"
    depends_on:
      - mariadb
    networks:
      - blog-network

volumes:
  mariadb-data:

networks:
  blog-network:
