name: Build and Deploy a blog application

on:
  push:
    branches:
      - cicd-pipeline

jobs:
  build-deploy:
    name: Build and Deploy a blog application using Spring Boot as backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run:
          mvn clean
          mvn -B package --file pom.xml