name: Build and Deploy a blog application

on:
  push:
    branches:
      - cicd-pipeline

jobs:
  build-deploy:
    name: Build and Deploy a blog application
    runs-on: ubuntu-latest

#    services:
#      mariadb:
#        image: mariadb
#        env:
#          MYSQL_ROOT_PASSWORD: root
#          MYSQL_DATABASE: blog
#          MYSQL_USER: user
#          MYSQL_PASSWORD: root
#        ports:
#          - "3306:3306"
#        volumes:
#          - data:/var/lib/mysql

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build with Maven
        run: mvn clean package -DskipTests

#      - name: Unit Tests
#        run: mvn -B test --file pom.xml
#
#      - name: Build
#        run: |
#          mvn clean
#          mvn -B package --file pom.xml

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/blog-backend:1.0.2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push image to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/blog-backend:1.0.2

#      - name: Build with Maven
#        run: mvn clean package -DskipTests

#      - name: Run tests
#        env:
#          SPRING_DATASOURCE_URL: jdbc:mariadb://localhost:3306/blog
#          SPRING_DATASOURCE_USERNAME: root
#          SPRING_DATASOURCE_PASSWORD: root
#        run: mvn test